# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EndWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 500)
        Form.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #abb8c3;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #abb8c3;\n"
"    border: 3px solid rgb(198, 0, 0);\n"
"    color: #000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(198, 0, 0);\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:rgb(191, 0, 0);\n"
"}")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(200, 40, 311, 70))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 120, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(420, 120, 201, 71))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(198, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 250, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.lbl_xp = QtWidgets.QLabel(Form)
        self.lbl_xp.setGeometry(QtCore.QRect(280, 250, 381, 50))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_xp.setFont(font)
        self.lbl_xp.setStyleSheet("color: rgb(198, 0, 0);")
        self.lbl_xp.setText("")
        self.lbl_xp.setObjectName("lbl_xp")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(60, 310, 240, 50))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.lbl_time = QtWidgets.QLabel(Form)
        self.lbl_time.setGeometry(QtCore.QRect(310, 310, 350, 50))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_time.setFont(font)
        self.lbl_time.setStyleSheet("color: rgb(198, 0, 0);")
        self.lbl_time.setText("")
        self.lbl_time.setObjectName("lbl_time")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(60, 370, 291, 50))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.lbl_hp = QtWidgets.QLabel(Form)
        self.lbl_hp.setGeometry(QtCore.QRect(370, 370, 291, 50))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hp.setFont(font)
        self.lbl_hp.setStyleSheet("color: rgb(198, 0, 0);")
        self.lbl_hp.setText("")
        self.lbl_hp.setObjectName("lbl_hp")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Поздравляем!!"))
        self.label_2.setText(_translate("Form", "Вы прошли игру "))
        self.label_3.setText(_translate("Form", "Doomrun"))
        self.label_4.setText(_translate("Form", "Ваш опыт :"))
        self.label_6.setText(_translate("Form", "Ваше время :"))
        self.label_8.setText(_translate("Form", "Ваше здоровье :"))
